<?php

// Editorial sources and contribution scope: docs/PORTFOLIO-CONTENT.md.
$full = ['role_ar' => 'التطوير الكامل للموقع', 'role_en' => 'Full-stack development'];
$items = [
    [
        'seed_key' => 'aether-school-os', 'slug' => 'aether-school-os',
        'name_ar' => 'Aether — منصة إدارة المدارس', 'name_en' => 'Aether School OS',
        'description_ar' => 'منصة تجمع إدارة المدارس والقبول والعمليات الأكاديمية والمالية في تجربة عربية وإنجليزية.',
        'description_en' => 'A bilingual school platform bringing admissions, academic operations and finance into one workspace.',
        'challenge_ar' => 'تنظيم عمليات مدارس متعددة مع الفصل بين بياناتها وربط العمل الأكاديمي والإداري.',
        'challenge_en' => 'Organize multiple schools while keeping their data separate and connecting academic and administrative workflows.',
        'solution_ar' => 'تطوير منصة تعتمد نطاق المدرسة لتنظيم البيانات، مع وحدات للقبول والطلاب والجداول والحضور والمالية وصلاحيات المستخدمين.',
        'solution_en' => 'Built a school-scoped platform with modules for admissions, students, timetables, attendance, finance and role-based access.',
        'outcomes_ar' => 'تجمع المنصة مسارات العمل الأساسية ضمن نظام قابل للتطوير. يستمر العمل على تحسين التجربة والوظائف.',
        'outcomes_en' => 'Core school workflows share a platform designed for further development. The experience and functionality remain under active development.',
        'url' => 'https://school112.laravel.cloud/', 'repository_url' => 'https://github.com/mo7ammedahmed/school',
        'category' => ['en' => 'Education platforms', 'ar' => 'المنصات التعليمية'],
        'skills' => ['PHP', 'Laravel', 'React', 'TypeScript', 'Inertia.js', 'Tailwind CSS'],
    ],
    [
        'seed_key' => 'al-noor-school', 'slug' => 'al-noor-school',
        'name_ar' => 'النور — نظام إدارة مدرسة', 'name_en' => 'Al Noor School',
        'description_ar' => 'نظام لمدرسة واحدة يربط الطلاب وأولياء الأمور بالحضور والتقييم والرسوم والتواصل.',
        'description_en' => 'A single-school management system connecting student and guardian records with attendance, assessment, fees and communication.',
        'challenge_ar' => 'جمع العمليات اليومية لمدرسة واحدة في واجهات تراعي اختلاف مسؤوليات الإدارة والمعلمين وأولياء الأمور.',
        'challenge_en' => 'Bring daily school operations together while respecting the different responsibilities of staff, teachers and guardians.',
        'solution_ar' => 'تطوير وحدات للطلاب والفصول والحضور والدرجات والرسوم، مع صلاحيات حسب الدور وواجهة عامة ثنائية اللغة.',
        'solution_en' => 'Developed student, class, attendance, grading and fee modules with role-based access and a bilingual public website.',
        'outcomes_ar' => 'يوفر النظام مكانًا موحدًا للمتابعة الأكاديمية والإدارية، مع استمرار تطويره.',
        'outcomes_en' => 'The system provides a shared workspace for academic and administrative follow-up and remains in development.',
        'url' => 'https://school-system.laravel.cloud/', 'repository_url' => 'https://github.com/mo7ammedahmed/school-system',
        'category' => ['en' => 'Education platforms', 'ar' => 'المنصات التعليمية'],
        'skills' => ['PHP', 'Laravel', 'React', 'TypeScript', 'Inertia.js', 'Tailwind CSS'],
    ],
    [
        'seed_key' => 'speed-rocket', 'slug' => 'speed-rocket',
        'name_ar' => 'سبيد روكيت', 'name_en' => 'Speed Rocket',
        'description_ar' => 'موقع شركة بالعربية والإنجليزية يعرض الخدمات والأعمال والمقالات مع أدوات لإدارة المحتوى.',
        'description_en' => 'A bilingual company website presenting services, projects and articles with tools for managing its content.',
        'challenge_ar' => 'تنظيم محتوى الشركة وتقديم خدماتها وأعمالها بطريقة قابلة للتحديث باللغتين.',
        'challenge_en' => 'Organize company content and present its services and work in two languages with an editable publishing workflow.',
        'solution_ar' => 'تطوير موقع Laravel بصفحات للخدمات والمشاريع والمقالات، ولوحة إدارة للمحتوى ونموذج تواصل.',
        'solution_en' => 'Built a Laravel website with service, project and article pages, content administration and a contact flow.',
        'outcomes_ar' => 'أصبحت الخدمات والأعمال والمقالات ضمن تجربة موحدة يمكن تحديث محتواها من الإدارة.',
        'outcomes_en' => 'Services, work and articles are presented in one experience with content maintained through administration tools.',
        'url' => 'https://speed-rocket.laravel.cloud/', 'repository_url' => 'https://github.com/mo7ammedahmed/speed-rocket-laravel',
        'category' => ['en' => 'Business websites', 'ar' => 'مواقع الشركات'],
        'skills' => ['PHP', 'Laravel', 'Alpine.js', 'Tailwind CSS'],
    ],
    [
        'seed_key' => 'anwan-print', 'slug' => 'anwan-print',
        'name_ar' => 'عنوان المحترف للطباعة والإعلان', 'name_en' => 'Anwan Print',
        'description_ar' => 'موقع لعرض خدمات الطباعة والإعلان والهوية البصرية وأعمال المنشأة ووسائل التواصل.',
        'description_en' => 'A business website showcasing printing, advertising and visual identity services, company work and contact information.',
        'challenge_ar' => 'تقديم خدمات متنوعة وأمثلة من أعمال الطباعة في موقع يسهل على العميل استكشافه.',
        'challenge_en' => 'Present a varied range of printing services and work examples in a website customers can explore.',
        'solution_ar' => 'تطوير الموقع لعرض الخدمات ومعرض الأعمال ومعلومات المنشأة والتواصل. يقتصر دوري هنا على تطوير الموقع، وليس تصميم المطبوعات المعروضة.',
        'solution_en' => 'Developed the website to present services, a work gallery, company information and contact details. My contribution is website development, not the design of the printed work shown.',
        'outcomes_ar' => 'يوفر الموقع مرجعًا رقميًا لخدمات المنشأة وأعمالها وقنوات التواصل معها.',
        'outcomes_en' => 'The website provides a digital reference for the company’s services, work and contact channels.',
        'url' => 'https://anwanprint.com/', 'repository_url' => null,
        'category' => ['en' => 'Business websites', 'ar' => 'مواقع الشركات'], 'skills' => [],
    ],
    [
        'seed_key' => 'shawerma-krakow', 'slug' => 'shawerma-krakow',
        'name_ar' => 'شاورما كراكوف', 'name_en' => 'Shawerma Krakow',
        'description_ar' => 'مساهمة في تطوير الواجهة الخلفية لموقع Shawerma Krakow.',
        'description_en' => 'Backend development for the Shawerma Krakow website.',
        'role_ar' => 'تطوير الواجهة الخلفية فقط', 'role_en' => 'Backend development only',
        'challenge_ar' => null, 'challenge_en' => null,
        'solution_ar' => 'تركزت مساهمتي على الواجهة الخلفية للموقع. لا تشمل هذه الدراسة نسبة تصميم الواجهة الأمامية إليّ.',
        'solution_en' => 'My contribution focused on the website’s backend. Frontend design is outside the scope of my contribution.',
        'outcomes_ar' => null, 'outcomes_en' => null,
        'url' => 'https://shawermakrakow.com/', 'repository_url' => null,
        'category' => ['en' => 'Backend development', 'ar' => 'تطوير الواجهة الخلفية'], 'skills' => [],
    ],
    [
        'seed_key' => 'portfolio', 'slug' => 'portfolio',
        'name_ar' => 'الموقع المهني ولوحة الإدارة', 'name_en' => 'Portfolio & Studio',
        'description_ar' => 'بورتفوليو عربي وإنجليزي مع لوحة لإدارة المشاريع والمحتوى والمظهر والتواصل والتحليلات.',
        'description_en' => 'A bilingual portfolio with a private studio for projects, content, appearance, inquiries and analytics.',
        'challenge_ar' => 'عرض الخبرة والأعمال مع إبقاء المحتوى والمظهر قابلين للإدارة من مكان واحد.',
        'challenge_en' => 'Showcase professional experience and work while keeping content and appearance manageable in one place.',
        'solution_ar' => 'تطوير واجهة React متصلة بـ Laravel عبر Inertia، مع إدارة المشاريع والمهارات والخبرات والثيمات ورسائل التواصل.',
        'solution_en' => 'Built a React experience connected to Laravel through Inertia, with management for projects, skills, experience, themes and contact messages.',
        'outcomes_ar' => 'أصبحت تجربة العرض وأدوات الإدارة جزءًا من تطبيق واحد ثنائي اللغة.',
        'outcomes_en' => 'The public presentation and its administration tools are part of one bilingual application.',
        'url' => 'https://mohammedahmed.laravel.cloud/', 'repository_url' => 'https://github.com/mo7ammedahmed/portfolio-2',
        'category' => ['en' => 'Web applications', 'ar' => 'تطبيقات الويب'],
        'skills' => ['PHP', 'Laravel', 'React', 'TypeScript', 'Inertia.js', 'Tailwind CSS'],
    ],
];

return array_map(static fn (array $item, int $index): array => [
    ...$full, ...$item,
    'status' => 'in_progress', 'is_visible' => true, 'is_featured' => $index < 3, 'sort_order' => $index,
    'cover' => 'database/content/images/'.$item['seed_key'].'.jpg',
], $items, array_keys($items));
